apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    appName: UIapp
    type: web1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels: 
    appName: UIapp
    type: web1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels: 
    appName: UIapp
    type: web2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels: 
    appName: UIapp
    type: web2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
