apiVersion: v1
kind: Pod
metadata:
  name: nginx01
  labels: 
    appName: UIapp
    type: web1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx02
  labels: 
    appName: UIapp
    type: web1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx03
  labels: 
    appName: UIapp
    type: web2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx04
  labels: 
    appName: UIapp
    type: web2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
