apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx01
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx02
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2